<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>697e85db-df6d-4c02-a667-f80fdf13457b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='card-list']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;gambar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5faec211-b494-400f-be54-df32638a6ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/storage/gym_images/esJ2Br13iE07D0sJ5erU37LojhsvY7tTrIZ9VZ4b.jpg</value>
      <webElementGuid>b2077079-02fe-4d09-bf3d-675792d38b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>gambar</value>
      <webElementGuid>180192da-29d7-4f77-a6b8-a182024ca0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-list&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;card-left&quot;]/img[1]</value>
      <webElementGuid>cdbeee30-2bce-46b9-800c-77d9cfe00ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-list']/div/div/div/img</value>
      <webElementGuid>287fe39c-e698-4ce3-bbe0-8333bb74d70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='gambar']</value>
      <webElementGuid>daece699-e530-4d50-ba95-f91b393c9d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ad9e5c3c-84e0-451a-b722-06f59953436d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://127.0.0.1:8000/storage/gym_images/esJ2Br13iE07D0sJ5erU37LojhsvY7tTrIZ9VZ4b.jpg' and @alt = 'gambar']</value>
      <webElementGuid>3e8090f2-df89-4e59-9381-b782a902e0dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
