<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Longitude_leaflet-marker-icon leaflet-z_9d5e38</name>
   <tag></tag>
   <elementGuidId>7a60fc29-69e1-4744-9e82-67b521f8c0eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapPolygon']/div/div[4]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mapPolygon > div.leaflet-pane.leaflet-map-pane > div.leaflet-pane.leaflet-marker-pane > img.leaflet-marker-icon.leaflet-zoom-animated.leaflet-interactive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4c2ee2dd-7538-45ce-b1a2-45676a99ff2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png</value>
      <webElementGuid>8144c3fa-ab21-45a9-8df2-3cc086fe636e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-marker-icon leaflet-zoom-animated leaflet-interactive</value>
      <webElementGuid>69581733-67ab-4478-ae30-be7e476083fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marker</value>
      <webElementGuid>a004749b-2d22-447b-bf68-2aaf0fde65f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d368140a-8659-4df5-93bf-2b3dbf1fa1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>431787fc-7395-4636-8aed-595bb49eca08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapPolygon&quot;)/div[@class=&quot;leaflet-pane leaflet-map-pane&quot;]/div[@class=&quot;leaflet-pane leaflet-marker-pane&quot;]/img[@class=&quot;leaflet-marker-icon leaflet-zoom-animated leaflet-interactive&quot;]</value>
      <webElementGuid>eec3719e-9be9-4288-8c18-84f108154062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mapPolygon']/div/div[4]/img</value>
      <webElementGuid>e9926720-ee42-4cfb-8405-e3b1b09eac82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Marker'])[2]</value>
      <webElementGuid>e12adfff-dc76-4318-82ee-8824e7f7a69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div[4]/img</value>
      <webElementGuid>366b96c8-5b48-4729-ba5b-5b416d29846e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png' and @alt = 'Marker']</value>
      <webElementGuid>9b6db759-ae25-413e-81ae-fbb2dee180fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
