<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bullets</name>
   <tag></tag>
   <elementGuidId>99f9acaf-7fe7-4d3d-b8bb-93f8db449270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.trix-button.trix-button--icon.trix-button--icon-bullet-list.trix-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6764f56-e3b0-479f-8402-b235360b6902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8b65540-bd52-4560-afd7-ae183822909d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trix-button trix-button--icon trix-button--icon-bullet-list trix-active</value>
      <webElementGuid>9a39456d-1d8b-467d-9e3f-7fb7fd3b20c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trix-attribute</name>
      <type>Main</type>
      <value>bullet</value>
      <webElementGuid>513fe580-4689-4c1a-a74c-7649d3f70852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bullets</value>
      <webElementGuid>a133427d-ed17-474e-80f2-9a8b8a7a616d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>751a14c4-ff6f-4965-91de-b20bc934c786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bullets</value>
      <webElementGuid>364752ef-8b3e-41c8-9495-8905b7d450cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trix-toolbar-1&quot;)/div[@class=&quot;trix-button-row&quot;]/span[@class=&quot;trix-button-group trix-button-group--block-tools&quot;]/button[@class=&quot;trix-button trix-button--icon trix-button--icon-bullet-list trix-active&quot;]</value>
      <webElementGuid>62c4bd3b-8336-4f33-a28c-13035013d832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>23385eba-c744-44e7-9ac8-f5cfbcd7a5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//trix-toolbar[@id='trix-toolbar-1']/div/span[2]/button[4]</value>
      <webElementGuid>78a3c07d-94cc-446b-af96-1dac1394c3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::button[1]</value>
      <webElementGuid>fea9cb5d-636f-47c0-a6dd-bd6c5d703700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quote'])[1]/following::button[2]</value>
      <webElementGuid>abbf127f-a12a-4f3f-b365-7d9231fddbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numbers'])[1]/preceding::button[1]</value>
      <webElementGuid>ee0824e2-7e28-4ac6-8cf2-c8f96a57089c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decrease Level'])[1]/preceding::button[2]</value>
      <webElementGuid>0c967e22-d8ac-49b4-b2cc-05db125a4372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bullets']/parent::*</value>
      <webElementGuid>76459c70-c6b1-4be5-9d1b-161baaffb310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button[4]</value>
      <webElementGuid>b48ac8af-cfac-450e-bb4d-01fc080635ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Bullets' and (text() = 'Bullets' or . = 'Bullets')]</value>
      <webElementGuid>7cd6f988-14b5-495b-adaa-c0c9c9bc65e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
