<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Koordinat LatLng(-6.878256, 107.60992) Leaflet</name>
   <tag></tag>
   <elementGuidId>a09bf7e7-5106-4ba6-b053-8820600cff7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapPolygon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mapPolygon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f8f362f-a781-4c48-bef5-457dc8cecb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mapPolygon</value>
      <webElementGuid>f338c03c-d8da-491e-a954-e09ea7d7aa66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>e90a8f2a-ac72-4d55-a9cf-f7ab1ade294d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>86db87ec-27b0-4318-83ea-a3d6cf876a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Koordinat: LatLng(-6.878256, 107.60992)×+− Leaflet</value>
      <webElementGuid>de22ce0f-ca35-473d-bcfe-794fb4e715ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapPolygon&quot;)</value>
      <webElementGuid>e98a1e7f-c003-49fb-b8fb-5205fda5b791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mapPolygon']</value>
      <webElementGuid>1a172d09-f28a-484b-ab7b-9af7dc1ea914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Longitude'])[2]/following::div[2]</value>
      <webElementGuid>81278cc7-2c11-4117-ad0c-b37259de03bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latitude'])[2]/following::div[3]</value>
      <webElementGuid>7a5bbd87-f496-4353-9297-ef5ec9b4a9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div</value>
      <webElementGuid>4ecdd3d5-c2af-431e-89ed-e7dfea74a31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mapPolygon' and (text() = 'Koordinat: LatLng(-6.878256, 107.60992)×+− Leaflet' or . = 'Koordinat: LatLng(-6.878256, 107.60992)×+− Leaflet')]</value>
      <webElementGuid>eb60af0e-69bf-48d6-b11d-efc127f2b161</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
