<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Koordinat LatLng(-6.878121, 107.609526)_15ab87</name>
   <tag></tag>
   <elementGuidId>640412b0-f90b-4ff6-8ba5-9195e6afd7a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapPolygon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mapPolygon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87266de7-bb63-4f0f-acf5-0ca1ee28a026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mapPolygon</value>
      <webElementGuid>c902b50b-2949-4715-9daf-89d9c1a8a90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>2e641cd4-d76f-4df2-a6bd-6f985af2f8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>faeeeaa3-8b6b-4a3b-bc91-f9e64755950f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Koordinat: LatLng(-6.878121, 107.609526)×+− Leaflet</value>
      <webElementGuid>25f0f1b1-3958-4438-8c37-b06f425d51fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapPolygon&quot;)</value>
      <webElementGuid>70a61e16-4eba-41bb-9bb4-e21cd953f3af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mapPolygon']</value>
      <webElementGuid>aa0693fa-0e60-4191-9ec7-62eebdd69f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Longitude'])[2]/following::div[2]</value>
      <webElementGuid>62a62169-b9fc-4b22-b479-68a60decbaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latitude'])[2]/following::div[3]</value>
      <webElementGuid>15fbc44e-8977-4655-b90f-077a3ed0931d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div</value>
      <webElementGuid>dfe1a622-ee3c-4a67-9042-d3fa46e13dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mapPolygon' and (text() = 'Koordinat: LatLng(-6.878121, 107.609526)×+− Leaflet' or . = 'Koordinat: LatLng(-6.878121, 107.609526)×+− Leaflet')]</value>
      <webElementGuid>a4230ca5-de3e-48a3-8c6f-ec44180cb7b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
