<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Koordinat LatLng(-6.878387, 107.609868)_af36c9</name>
   <tag></tag>
   <elementGuidId>9ac9c116-86f9-44ab-9494-6d8651dbc83a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapPolygon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mapPolygon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de65f541-4441-431b-bd98-4c6e4919b40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mapPolygon</value>
      <webElementGuid>0052bcf0-89d9-49a9-9aa5-0465a70d44e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>9d4dd64e-2b76-4d34-9823-3bd6467c2906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f9d03e3c-d1c0-4577-9f32-e6301149dd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Koordinat: LatLng(-6.878387, 107.609868)×+− Leaflet</value>
      <webElementGuid>ccce399c-ae1a-462a-8cbf-c1a77390b216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapPolygon&quot;)</value>
      <webElementGuid>75eb883a-752f-40d6-8735-2a613e2e7fe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mapPolygon']</value>
      <webElementGuid>1cb82132-835a-4e27-a188-38ff3ba329ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Longitude'])[2]/following::div[2]</value>
      <webElementGuid>256cdab2-dc99-4a4d-864d-bc87fa7ef1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latitude'])[2]/following::div[3]</value>
      <webElementGuid>7f4aea1f-d7d3-48e0-ad2e-4cc0678d92bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div</value>
      <webElementGuid>ba3d25eb-1047-48f2-bb9e-c754dddd2114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mapPolygon' and (text() = 'Koordinat: LatLng(-6.878387, 107.609868)×+− Leaflet' or . = 'Koordinat: LatLng(-6.878387, 107.609868)×+− Leaflet')]</value>
      <webElementGuid>3c51e372-0af3-4dae-8e27-9a5518590061</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
